### ISSUE TITLE
flv播放失败

### ISSUE THREAD

**Issue by AimLuo** [goblin-laboratory/reactjs-player#117]
- 测试链接：http://nebula-playback.qiniudn.com/test-playback/flv/sample.flv
- 测试环境：window10，chrome77.0.3865.120（正式版本） （64 位）
![image](https://user-images.githubusercontent.com/21124342/67647183-48857200-f96c-11e9-8fae-cf0f7911df69.png)

flv地址是随便搜的，vlc可以播放

**Comment by AimLuo** [comment]
好像是视频问题，

**Comment by xiaosongxiaosong** [comment]
我的 demo 里面 flv.js 都是给的直播参数，没有测试过 flv.js 播回放的情况，如果有测试地址我这边可以把 demo 增加一个播录像的选项，同理 hls.js 都是用来播回放的

**Comment by xiaosongxiaosong** [comment]
这个 url 是 http 的，demo 地址是 https 的，所以会没办法播放 @AimLuo

**Comment by AimLuo** [comment]
看到了，而且还有跨域问题。

**Comment by AimLuo** [comment]
flv.js有跨域限制。😭
```javascript;
import React from 'react';
import ReactPlayer from 'reactjs-player';
import './App.css';
export default () => {
  return <ReactPlayer kernel="flvjs" src="http://47.110.238.135:8018/mailian/07466BFE7481_1.flv" type="video/x-flv" />
}
```
![image](https://user-images.githubusercontent.com/21124342/67655779-bc377700-f98c-11e9-84fa-d85c147adc1c.png)

**Comment by AimLuo** [comment]
跨域用nginx代理应该可行，不过我们项目的流有问题，

- [ ] 有待验证

![image](https://user-images.githubusercontent.com/21124342/67730613-759b5880-fa30-11e9-9df4-557a7b3b2faf.png)

**Comment by xiaosongxiaosong** [comment]
@AimLuo  
1. 可以先用 flv.js 测试下，我这边对于视频没有做过多的处理，可能参数调一下就能适配，flv 格式标准就不是那么严格
2. 跨域的问题可以再后端配置一下下面两个响应头：
```
access-control-allow-headers: *
access-control-allow-origin: *
```
