### ISSUE TITLE
华为手机微信同层播放显示异常

### ISSUE THREAD

**Issue by xiaosongxiaosong** [goblin-laboratory/reactjs-player#12]
### 问题页面
https://goblin-laboratory.github.io/react-player/

### 手机型号
华为手机 P10 青春版（水滴屏）

### 问题现象
1. 开始播放时，进入同层播放状态，水滴屏的工具栏显示正常，其他区域有半透明蒙板
![微信图片_20190619154231](https://user-images.githubusercontent.com/2703455/59746388-6b5e9600-92a9-11e9-8f56-e3f9c85c223c.jpg)

2. 旋转手机，视频还是有半透明蒙板
![微信图片_20190619154224](https://user-images.githubusercontent.com/2703455/59746540-b7113f80-92a9-11e9-9bf2-0bcfbd822353.jpg)

3. 回到竖屏状态，页面下移，从水滴屏工具栏下方开始
![微信图片_20190619154216](https://user-images.githubusercontent.com/2703455/59747184-f1c7a780-92aa-11e9-99be-2e1f21e8c096.jpg)

**Comment by AimLuo** [comment]
华为就是个异类，以前做移动端的时候，就华为各种奇葩问题

**Comment by xiaosongxiaosong** [comment]
是挺多问题的，但是没办法也要适配才行 @AimLuo

**Comment by AimLuo** [comment]
所以我选择不做移动端。

**Comment by xiaosongxiaosong** [comment]
任性🤙🤙🤙

**Comment by xiaosongxiaosong** [comment]
微信最新的版本中支持了页面内播放，这个问题不存在了
