### ISSUE TITLE
缺少swf解析模块

### ISSUE THREAD

**Issue by AimLuo** [goblin-laboratory/reactjs-player#121]
![image](https://user-images.githubusercontent.com/21124342/67667515-f44cb300-f9a8-11e9-8668-f77d2dabe04f.png)
然后装了[swf-loader](https://github.com/openfl/swf-loader)
```javascript;
    {
      test: /\.swf$/,
      use: [
        {
          loader: 'swf-loader'
        }
      ],
    }
```
![image](https://user-images.githubusercontent.com/21124342/67667639-2fe77d00-f9a9-11e9-81eb-b8828928e607.png)

**Comment by AimLuo** [comment]
解决了，把文件丢到了运行时的根目录
```
const grindPlayerSwf = './GrindPlayer.swf'
const flashlsOSMFSwf = './flashlsOSMF.swf'
```

**Comment by AimLuo** [comment]
原来有默认值😂
![image](https://user-images.githubusercontent.com/21124342/67731360-db88df80-fa32-11e9-9f50-3208f5aabd74.png)

**Comment by xiaosongxiaosong** [comment]
建议还是自己服务器上面放一个，这个默认值用的 unpkg 的 cdn 地址，有被墙的风险 @AimLuo
