### ISSUE TITLE
父级容器记得加`relative`

### ISSUE THREAD

**Issue by AimLuo** [goblin-laboratory/reactjs-player#122]
父级容器记得加`relative`
```
<div style={{
  height: '100%',
  position: 'relative'
}} >
  <ReactPlayer src={foo} />
</div>
````

**Comment by AimLuo** [comment]
😂react-swf尺寸小于400*300的视频不能自动播放

**Comment by xiaosongxiaosong** [comment]
这个限制是浏览器对flash的限制，两个问题等我手头事情忙完了补充到 FAQ 中

**Comment by AimLuo** [comment]
用video.js的flash也不能播放，并且告警：
![image](https://user-images.githubusercontent.com/21124342/67825042-0e020d80-fb03-11e9-8d25-75b16f2db8a9.png)
我使用了第三方编译的swf文件，就可以了。
[自编译](http://www.penggy.cc/2017/11/03/VideoJS%20%E7%BD%91%E9%A1%B5%E7%9B%B4%E6%92%AD%E5%AE%9E%E7%8E%B0%E9%BB%98%E8%AE%A4%E9%9D%99%E9%9F%B3/)
里面有个图片丢失，这里补上
![image](https://user-images.githubusercontent.com/21124342/67825547-a0ef7780-fb04-11e9-837c-ff2674cc24cc.png)

[下载地址](https://www.liveqing.com/docs/download/LivePlayer.html)下载那个播放器，里面的liveplayer.swf
![image](https://user-images.githubusercontent.com/21124342/67825215-87016500-fb03-11e9-9a59-849a85a7427e.png)

**Comment by xiaosongxiaosong** [comment]
那可能是 GrindPlayer 的限制，我一直以为 flash 都是这样的呢😥

**Comment by AimLuo** [comment]
浏览器安全设置就是小于这个尺寸的视频不能自动播放，但是有些例外：  
原生video，设置**静音**就能自动播放。
```javascript
<video autoPlay muted loop style={{
  height: 165,
  width: 309,
  display: 'block',
  backgroundColor: 'black',
  objectFit: 'fill'
}} src='foo.mp4' />
```

- [ ] falsh需要研究，自行编译react-swf的swf文件，实现小尺寸自动播放

另外音频audio，可以用一段空白音频实现自动播放。
```javascript
const audioIframe = document.createElement('iframe')
audioIframe.allow = "autoplay"
audioIframe.style = "display:none"
audioIframe.src = `foo/voice/empty.m4a`
document.body.appendChild(audioIframe);
```
然后在代码中播放其他带声音的音频

**Comment by AimLuo** [comment]
empty.m4a空白音频可以用window10的录音机录制，此时可以将耳机插入话筒孔，实现空白录制。  
建议用m4a格式，优点请自行查询。

**Comment by AimLuo** [comment]
> 那可能是 GrindPlayer 的限制，我一直以为 flash 都是这样的呢😥

videojs的flash也限制了，需要自己编译swf才行。

**Comment by xiaosongxiaosong** [comment]
### 自动播放

这个项目目前没有强制做自动播放的计划，打开页面自动播放在我看来并不是最好的体验

### flash

grindplayer 是目前用户的 flash player 中体验比较好的，接口和文档都比较不错，现在已经在抽时间封装 grindplayer ，也没有替换的打算

**Comment by AimLuo** [comment]
`flash` 已死，不要浪费时间去研究 flash` 了。
