### ISSUE TITLE
package.json 配置文件的问题

### ISSUE THREAD

**Issue by CaiJingLong** [goblin-laboratory/reactjs-player#370]
我在实际使用中，会遇到
Can't resolve 'fbemitter' ./node_modules 等错误，我查看了 package.json，发现了依赖都定义在了 devDependencies 节点内，我感觉应该是放错位置了，你本地开发理论上是没问题的，但是如果直接 npm/yarn 添加依赖就报错了

https://github.com/goblin-laboratory/reactjs-player/blob/15e53f2e38f640c8f9f35311d5fd4f21fa7f7b14/package.json#L35-L73

**Comment by xiaosongxiaosong** [comment]
peerDependencies 里面的库都是要加到项目中的，可以看看下面的博客了解一下哈

https://www.cnblogs.com/wonyun/p/9692476.html

![image](https://user-images.githubusercontent.com/2703455/170158413-a4d0c75b-cc42-4f46-a9e3-4110154d5527.png)
