### ISSUE TITLE
一点就黑屏, native方式播放mp4

### ISSUE THREAD

**Issue by chenxiaolei** [goblin-laboratory/reactjs-player#91]
demo就是如此, 点击后<video> 的src被清空

**Comment by xiaosongxiaosong** [comment]
在手机上吗？demo 页没有支持 native 模式，可以贴下代码吗？

**Comment by xiaosongxiaosong** [comment]
我今天更像下demo页，PC 端支持 native 方式播放 mp4，我自己先测试看看

**Comment by xiaosongxiaosong** [comment]
@chenxiaolei 
demo 页已经更新了，PC 端支持 mp4 播放，在测试下看看，有问题的麻烦提供一下浏览器useragent和播放的 src 地址信息，多谢！！
https://goblin-laboratory.github.io/reactjs-player/
